name: PServerPanelUIPlusE
author: pbol377
version: 1.5
api: 
- 4.0.0
- 3.3.0
- 3.2.5
- 3.0.0
- 3.1.0
- 3.3.1
- 3.3.2
- 3.3.3

main: PSPUI\ui

commands:
 sv:
  description: "Open Server UI"
  default: OP
